# Netlify configuration for PetBook
# Stable SPA-style routing: always fall back to index.html for unknown routes.
# Do NOT redirect all routes to /compte.html (this caused the "always on account page" bug).

[build]
  publish = "."

[[redirects]]
  from = "/mon-compte"
  to   = "/compte.html"
  status = 200

# SPA fallback — very important to keep the site reachable at / (home) and all public pages
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Security headers (optional but nice)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
